def analyze_diseases(query):
    query = query.lower()
    if "Rust corn".lower() in query:
        return "To manage corn rust effectively, farmers have multiple options: hybrid selection, scouting, cultural practices, and fungicides. Hybrid selection for genetic disease resistance is key, although complete resistance is rare. Regular scouting helps catch diseases early. Fungicides can be used preventatively, especially in high-yield corn, for optimal results. Timing is crucial for fungicide application, with early treatment being most effective."
    elif "Corn gray leaf spot".lower()  in query:
        return "Preventative measures like using less susceptible corn products, crop rotation, residue removal, and tillage help reduce gray leaf spot impact. Regular scouting from V-10 to V-14 is crucial, with fungicide application recommended from tasseling through early silk growth stages if disease presence is detected and weather favors it. Strobilurin-based fungicides are effective against gray leaf spot when applied during this period."
    elif "Potato Early Blight".lower()  in query:
        return "Effective management of potato early blight involves an integrated approach, utilizing cultural practices and foliar fungicides. Cultural methods include crop rotation, weed control, timing irrigation to minimize leaf wetness, fall tillage, and using disease-free seed. Cultivar selection also plays a role, with earlier maturing varieties being slightly more susceptible. Regular scouting from 12 inches in height onwards and using P-Day calculations help predict infection risk, guiding management actions like fungicide application."
    elif "Potato late blight".lower()  in query:
        return "To detect and prevent potato late blight, employ fungicides containing spores like fluazinam, Dithane (mancozeb) MZ, Tattoo C, or Acrobat MZ, implement cultural practices such as removing volunteer potatoes and controlling weed hosts, and treat tubers with a 1:1000 mercuric chloride solution or phosphorous acid before storage to inhibit mycelium growth and prevent infection."
    elif "tomato target spot".lower()  in query:
        return "To manage target spot on tomatoes, regularly apply fungicides before symptoms appear, ensuring full coverage of plant surfaces. Consult regional guides for recommended products, including chlorothalonil, mancozeb, copper oxychloride, azoxystrobin, pyraclostrobin, boscalid, and acibenzolar-S-methyl. Rotate or tank-mix fungicides with different modes of action to prevent resistance development, particularly with strobilurin fungicides. Integrated programs combining cultural and chemical strategies are crucial for long-term management."
    elif "tomato bacterial spot".lower()  in query:
        return "To manage bacterial spot in tomatoes, focus on growing healthy plants from infection-free seeds and handling seedlings carefully during transplantation. Cultural controls are crucial due to the difficulty of managing the disease with chemicals, which can be washed off by heavy rain. Before planting, use disease-free seeds, treat seeds with hot water if necessary, keep nurseries away from fields, inspect seedlings thoroughly, and remove infected plants. During growth, avoid overhead irrigation, minimize water splashing, apply mulch, and avoid working in wet crops. After harvest, collect and burn plant debris, rotate crops, and consider resistant varieties for peppers. For chemical control, use copper fungicides or copper plus mancozeb, starting with nursery treatments and continuing every 7-10 days in the field, especially during wet weather. Early spraying is crucial for young plants."
    else: 
        return f"Your plant is healthy"